services:

  client:
    build: ./client
    container_name: payx-client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - server
    
  server:
    build: ./server
    container_name: payx-server
    env_file:
      - ./server/.env
    depends_on:
      - bank
    

  bank:
    build: ./bank
    container_name: payx-bank
    env_file:
      - ./bank/.env
    